package org.robobinding.customviewbinding;

import org.robobinding.viewbinding.BindingAttributeMappings;
import org.robobinding.viewbinding.ViewBinding;

import com.google.common.base.Preconditions;

/**
 * @since 1.0
 * @author Cheng Wei
 *
 */
public class CustomViewBinding<ViewType> {
	
	/**
	 * Implement the method to supply any other binding implementations that are not simple one-way property attributes 
	 * which can be auto-generated by the framework via {@link org.robobinding.annotation.ViewBinding} annotation.
	 */
	public void mapBindingAttributes(BindingAttributeMappings<ViewType> mappings) {
	}
	
	/**
	 * When you want to extend the existing ViewBinding implementation currently registered in the framework by providing
	 * more attribute binding implementations or override some of them.
	 */
	public final CustomViewBindingDescription extend(Class<ViewType> viewClass) {
		checkViewClass(viewClass);
		
		ViewBinding<ViewType> viewBinding = loadViewBinding();
		return new CustomViewBindingDescription(viewClass, 
				new ExtensionViewBindingApplier<ViewType>(viewClass, viewBinding));
	}

	private void checkViewClass(Class<ViewType> viewClass) {
		Preconditions.checkNotNull(viewClass, "viewClass must not be null");
	}

	private ViewBinding<ViewType> loadViewBinding() {
		ViewBindingLoader loader = new ViewBindingLoader();
		return loader.load(this);
	}
	
	/**
	 * When you want to override the existing ViewBinding implementation currently registered in the framework.
	 * Use the your own one instead.
	 */
	public final CustomViewBindingDescription forView(final Class<ViewType> viewClass) {
		checkViewClass(viewClass);
		
		ViewBinding<ViewType> viewBinding = loadViewBinding();
		return new CustomViewBindingDescription(viewClass, 
				new OverridingViewBindingApplier<ViewType>(viewClass, viewBinding));
	}
}
