Versions
========
:Revision: 0.8.8
:toc:
:numbered:
:imagesdir: ./images
:source-highlighter: pygments

version 0.8.8(released 26/09/2014)
----------------------------------
* https://github.com/RoboBinding/RoboBinding/issues/176[bug #176]
multiple two-way bindings to same property is not working.
* https://github.com/RoboBinding/RoboBinding/issues/178[bug #178]
NullPointer in Android 4.4 KitKat with spinner in horizontal oriented LinearLayout. 
Affected by this bug, there are some *API changes* to org.robobinding.ViewBinder and org.robobinding.binder.Binders.

version 0.8.7(released 24/09/2014)
----------------------------------
* https://github.com/RoboBinding/RoboBinding/issues/172[bug #172]
NullPointer when invoking a setter in the contructor of a PresentationModel with AspectJ.
* https://github.com/RoboBinding/RoboBinding/issues/174[improvement #174] 
Removed the need of org.robobinding.itempresentationmodel.AbstractItemPresentationModel to prevent confusion.
* https://github.com/RoboBinding/RoboBinding/issues/170[new feature #170] 
Safeguard the updates to PresentationModels only executed within UI thread.

version 0.8.6(released 20/09/2014)
----------------------------------
* Made a change to the PresentationModel AspectJ approach. 
It is now required to explicitly define a PresentationModelChangeSupport field in a presentation model 
in order to use the methods like firePropertyChange("propertyName");
* Made a minor change to proguard config.
* Clean up the javadocs. Now it only includes the public APIs.
* Upgraded framework and all sample projects to Gradle build.
* Upgraded to Robolectric 2.3 for tests.