版本
====
:Revision: 0.8.10
:toc:
:numbered:
:imagesdir: ./images
:source-highlighter: pygments

版本 0.8.10(02/08/2015发布)
---------------------------
* https://github.com/RoboBinding/RoboBinding/issues/185[feature #185]
静态源代码产生 ViewBinding 的方式替代旧的动态绑定 DynamicViewBinding。对
https://github.com/RoboBinding/RoboBinding/blob/develop/framework/src/main/java/org/robobinding/viewbinding/ViewBinding.java[ViewBinding]接口进行了更新。
新的
https://github.com/RoboBinding/RoboBinding/blob/develop/framework/src/main/java/org/robobinding/customviewbinding/CustomViewBinding.java[CustomViewBinding]
接口替代了旧的 DynamicViewBinding 接口。 移除了一些简单的单向绑定实现，RoboBinding不需要包含这些，因为要使用它们的时候，只要简单的声明即可。
如
https://github.com/RoboBinding/RoboBinding-gallery/blob/master/app/src/main/java/org/robobinding/gallery/activity/GalleryApp.java[ViewBindingForView, MenuItemBinding and MenuItemGroupBinding]
示例。还有 https://github.com/RoboBinding/RoboBinding-gallery/blob/master/app/src/main/java/org/robobinding/gallery/model/customcomponent/TitleDescriptionBarBinding.java[自定义组件]绑定声明示例。
* https://github.com/RoboBinding/RoboBinding/issues/210[feature #210]
启用 Sourcegraph。
* https://github.com/RoboBinding/RoboBinding/issues/217[issue #217]
  https://github.com/RoboBinding/RoboBinding/issues/222[issue #222]
  https://github.com/RoboBinding/RoboBinding/issues/218[issue #218]
buildToolsVersion v21以上绑定失效。
* https://github.com/RoboBinding/RoboBinding/issues/221[issue #221]
当一个自定义类在两个以上绑定属性上使用时，产生的源代码编译出错，因为自定义类的import语句不见了。
* https://github.com/RoboBinding/RoboBinding/issues/209[issue #209]
当一个itemPresentationModel factory方法被多个lists用时，编译出错。
* https://github.com/RoboBinding/RoboBinding/issues/200[issue #200]
appcompat-v7 -- lost styles，在appcompat-v7下styles没了。
* https://github.com/RoboBinding/RoboBinding/issues/194[issue #194]
java.lang.ClassNotFoundException: 找不到 "android.widget.fragment" 类。

版本 0.8.9(2014-10-14发布)
--------------------------
* https://github.com/RoboBinding/RoboBinding/issues/181[新特性 181]
ItemPresentationModel.updateData()增加了itemView的信息。这样当需要时可以用Android原生的方式。
* https://github.com/RoboBinding/RoboBinding/issues/48[新特性 48]
用自动源代码生成来替代Java反射来提高性能。
关于源代码生成的设置，请参考 link:getting_started.zh.html#_开发环境[环境设置]部分。
通过引入源代码生成，编写PresentationModel得到进一步的简化。
PresentationModel只需要实现org.robobinding.presentationmodel.HasPresentationModelChangeSupport接口(AbstractPresentationModel 已经被移除).
详细信息，请参考 link:getting_started.zh.html#_presentation_models[Presentation Models].

版本 0.8.8(2014-09-26发布)
--------------------------
* https://github.com/RoboBinding/RoboBinding/issues/176[bug #176]
多个双向视图属性同时绑定到PresentationModel的同一个属性时，有时候会出错。
* https://github.com/RoboBinding/RoboBinding/issues/178[bug #178]
在Android 4.4版本后，在LinearLayout里包含spinner并且orientation为horizontal时出现NullPointer。
受这个bug的影响，org.robobinding.ViewBinder 与 org.robobinding.binder.Binders *API有些变更* 。

版本 0.8.7(2014-09-24发布)
---------------------------
* https://github.com/RoboBinding/RoboBinding/issues/172[bug #172]
使用带有AspectJ的PresentationModel时，在构造函数里调用setter抛出NullPointer。
* https://github.com/RoboBinding/RoboBinding/issues/174[优化 #174]
去掉了org.robobinding.itempresentationmodel.AbstractItemPresentationModel，避免混淆。
* https://github.com/RoboBinding/RoboBinding/issues/170[新特性 #170]
增加了对Presentation 更新操作的限制，只能在UI thread里进行。

版本 0.8.6(2014-09-20发布)
---------------------------
* 更新了以AspectJ方式实现Presentation Model。现在要调用像方法firePropertyChange("propertyName")，需要显式定义一个PresentationModelChangeSupport成员变量。
* 对Proguard配置进行了小的更新。
* 更新了JavaDocs，只包含公共的APIs。
* 更新了所有的项目，都使用Gradle构建方式。
* 将Robolectric升级到版本2.3。
